openapi: 3.0.1

info:
   title: API de Pedido
   description: API para gerenciamento de pedidos, clientes, endereços e pagamentos.
   version: 1.0.0
servers:
   - url: http://localhost:8887/v1/api
     description: server url

paths:
   /orders/{orderNumber}:
      get:
         summary: "Busca um pedido pelo número do pedido"
         description: "Este endpoint retorna os detalhes de um pedido específico com base no número do pedido fornecido."
         operationId: "getOrder"
         parameters:
            - name: "orderNumber"
              in: "path"
              required: true
              description: "Número único do pedido."
              schema:
                 type: string
                 example: "1234567890"  # Exemplo do valor do orderNumber
         responses:
            '200':
               description: "Pedido encontrado com sucesso"
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Order'
            '404':
               description: "Pedido não encontrado"
            '400':
               description: "Requisição inválida"
            '500':
               description: "Erro interno do servidor"

components:
   schemas:
      DeliveryAddress:
         type: object
         description: Representa o endereço de entrega de um pedido.
         properties:
            addressDescription:
               type: string
               description: "Descrição do endereço (ex.: Apto 101, Bloco A)"
               example: "Rua das Flores, 123, Apto 101"
            cep:
               type: string
               description: Código postal do endereço.
               example: "12345-678"
            id:
               type: integer
               format: int64
               example: 1
               description: Identificador único.
            city:
               type: string
               description: Nome da cidade do endereço.
               example: "São Paulo"
            state:
               type: string
               description: Sigla do estado do endereço.
               example: "SP"
            number:
               type: string
               description: "Número do endereço (ex.: número da casa ou apartamento)"
               example: "123"
            contactPhone:
               type: string
               description: Número de telefone de contato.
               example: "(11) 98765-4321"
            recipientName:
               type: string
               description: Nome do destinatário da entrega.
               example: "João Silva"

      Customer:
         type: object
         description: Representa um cliente da loja.
         properties:
            id:
               type: integer
               format: int64
               description: Identificador único do cliente.
               example: 1234
            customerId:
               type: integer
               format: int64
               description: ID do cliente no sistema.
               example: 34533
            documentNumber:
               type: string
               description: Número do CPF ou CNPJ do cliente.
               example: "123.456.789-00"
            email:
               type: string
               description: Endereço de e-mail do cliente.
               example: "joao.silva@example.com"
            name:
               type: string
               description: Nome completo do cliente.
               example: "João Silva"

      Discount:
         type: object
         description: Representa um desconto aplicado a um pedido.
         properties:
            order:
               $ref: '#/components/schemas/Order'
            discountValue:
               type: number
               format: float
               description: Valor absoluto do desconto.
               example: 20.00
            percentageDiscount:
               type: number
               format: float
               description: Porcentagem de desconto aplicada.
               example: 10
            discountType:
               type: string
               description: "Tipo do desconto (ex.: percentua, fixo)."
               example: "percentual"
            createdAt:
               type: string
               format: date-time
               description: Data e hora de criação do desconto.
               example: "2024-11-21T10:30:00"
            id:
               type: integer
               format: int64
               example: 1
               description: Identificador único.
            updatedAt:
               type: string
               format: date-time
               description: Data e hora da última atualização do desconto.
               example: "2024-11-21T12:00:00"

      OrderItem:
         type: object
         description: Representa um item dentro de um pedido.
         properties:
            totalItem:
               type: number
               format: float
               description: Valor total do item (quantidade * preço unitário).
               example: 50.00
            quantity:
               type: integer
               description: Quantidade do produto no pedido.
               example: 2

            unitPrice:
               type: number
               format: float
               description: Preço unitário do item.
               example: 25.00
            productId:
               type: string
               description: Identificador único do produto.
               example: "P12345"
            productName:
               type: string
               description: Nome do produto.
               example: "Produto X"
            id:
               type: integer
               format: int64
               example: 1234
               description: Identificador único do item do pedido.
            discount:
               $ref: '#/components/schemas/Discount'


      Order:
         type: object
         description: Representa um pedido feito pelo cliente.
         properties:
            id:
               type: integer
               format: int64
               description: Identificador único do pedido.
               example: 12345
            orderNumber:
               type: string
               description: Número do pedido.
               example: "1001"
            independentKey:
               type: string
               description: Chave independente do pedido.
               example: "UNIQUEKEY123"
            modificationDate:
               type: string
               format: date-time
               description: Data e hora da última modificação do pedido.
               example: "2024-11-21T12:00:00"
            creationDate:
               type: string
               format: date-time
               description: Data e hora de criação do pedido.
               example: "2024-11-20T15:30:00"
            totalValue:
               type: number
               format: float
               description: Valor total do pedido (incluindo todos os itens e descontos).
               example: 150.00
            itemsTotalValue:
               type: number
               format: float
               description: Valor total dos itens sem os descontos.
               example: 170.00
            itemsDiscountTotalValue:
               type: number
               format: float
               description: Valor total dos descontos aplicados nos itens.
               example: 20.00
            billingDate:
               type: string
               format: date-time
               description: Data de faturamento do pedido.
               example: "2024-11-21T10:00:00"
            dateSale:
               type: string
               format: date-time
               description: Data da venda.
               example: "2024-11-20T14:00:00"
            status:
               $ref: '#/components/schemas/OrderStatus'
            customer:
               $ref: '#/components/schemas/Customer'
            deliveryAddress:
               $ref: '#/components/schemas/DeliveryAddress'
            paymentMethods:
               type: array
               items:
                  $ref: '#/components/schemas/PaymentMethod'
            items:
               type: array
               items:
                  $ref: '#/components/schemas/OrderItem'

      OrderStatus:
         type: object
         description: Representa o status de um pedido.
         properties:
            status:
               type: string
               description: Status atual do pedido.
               example: "Pendente"
            id:
               type: integer
               format: int64
               example: 1
               description: Identificador único do status.

      PaymentMethod:
         type: object
         description: Representa um método de pagamento utilizado no pedido.
         properties:
            paymentMethodId:
               type: string
               description: Identificador do método de pagamento.
               example: "PM12345"
            paymentDate:
               type: string
               format: date-time
               description: Data e hora do pagamento.
               example: "2024-11-21T11:30:00"
            acquirerName:
               type: string
               description: "Nome da adquirente (ex.: Cielo)."
               example: "Cielo"
            cardId:
               type: string
               description: Identificador do cartão utilizado.
               example: "CARD12345"
            id:
               type: integer
               format: int64
               description: Identificador único do pagamento.
               example: 1245
            numberCard:
               type: string
               description: Número do cartão utilizado.
               example: "1234-5678-9876-5432"
            totalValue:
               type: number
               format: float
               description: Valor total pago.
               example: 150.00

